---
# https://docs.readthedocs.io/en/latest/config-file/
version: 2

formats:
  - htmlzip

build:
  os: "ubuntu-24.04"
  tools:
    python: "3.12"

python:
  install:
    - requirements: dev-deps/docs.txt
    - method: pip
      path: .

sphinx:
  configuration: docs/conf.py
  fail_on_warning: true
